SELECT YEAR(SALES_DATE) AS YEAR
           ,MONTH(SALES_DATE) AS MONTH
, COUNT(DISTINCT U.USER_ID) AS PUCHASED_USERS
, ROUND((COUNT(DISTINCT O.USER_ID)/(SELECT COUNT(*) 
                                  FROM USER_INFO 
                                  WHERE YEAR(JOINED) = '2021'))
         , 1) as PUCHASED_RATIO
FROM USER_INFO U, ONLINE_SALE O
WHERE U.USER_ID = O.USER_ID
AND YEAR(JOINED) = '2021'
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR, MONTH;