-- 코드를 입력하세요
SELECT EXTRACT(YEAR FROM SALES_DATE) AS YEAR
           ,EXTRACT(MONTH FROM SALES_DATE) AS MONTH
, COUNT(DISTINCT U.USER_ID) AS PUCHASED_USERS
, ROUND((COUNT(DISTINCT O.USER_ID)/(SELECT COUNT(*) 
                                  FROM USER_INFO 
                                  WHERE TO_CHAR(JOINED, 'YYYY') = '2021'))
         , 1) as PUCHASED_RATIO
FROM USER_INFO U, ONLINE_SALE O
WHERE U.USER_ID = O.USER_ID
AND TO_CHAR(JOINED, 'YYYY') = '2021'
GROUP BY EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE)
ORDER BY YEAR, MONTH;